package model;

// Generated 6 Feb, 2016 11:54:43 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Slot generated by hbm2java
 */
@Entity
@Table(name = "slot")
public class Slot implements java.io.Serializable {

	private Integer slotId;
	private Integer beedNumber;
	private Integer status;
	private Date availDate;
	private Integer blockStatus;
	private Integer token;

	public Slot() {
	}

	public Slot(Integer beedNumber, Integer status, Date availDate,
			Integer blockStatus, Integer token) {
		this.beedNumber = beedNumber;
		this.status = status;
		this.availDate = availDate;
		this.blockStatus = blockStatus;
		this.token = token;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "slot_id", unique = true, nullable = false)
	public Integer getSlotId() {
		return this.slotId;
	}

	public void setSlotId(Integer slotId) {
		this.slotId = slotId;
	}

	@Column(name = "beed_number")
	public Integer getBeedNumber() {
		return this.beedNumber;
	}

	public void setBeedNumber(Integer beedNumber) {
		this.beedNumber = beedNumber;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "avail_date", length = 19)
	public Date getAvailDate() {
		return this.availDate;
	}

	public void setAvailDate(Date availDate) {
		this.availDate = availDate;
	}

	@Column(name = "block_status")
	public Integer getBlockStatus() {
		return this.blockStatus;
	}

	public void setBlockStatus(Integer blockStatus) {
		this.blockStatus = blockStatus;
	}

	@Column(name = "token")
	public Integer getToken() {
		return this.token;
	}

	public void setToken(Integer token) {
		this.token = token;
	}

}
